---
process:
  id: 1
  pkt_thres: 0
  has_ispf: false
  has_bfd: true
  has_ttlsec: true
  ref_bw: 100
  spf:
    init: 50
    min: 200
    max: 5000

all_areas:
  area0:
    type: standard  # valid values: standard, stub, nssa
    routers: 2
    drs: 1
    has_frr: true
    max_lsa3: 333
    max_lsa5: 555
  area51:
    type: nssa
    routers: 1
    drs: 0
    has_frr: true
    max_lsa7: 777
  area300:
    type: stub
    routers: 1
    drs: 0
    max_lsa3: 333
...
