---
ci_test: false
ansible_user: "ansible"
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65663132306164613936316364333031383963316165623734366431646431386538346136643131
          3263313761393332373133633332366239333439636530320a386538303035616461356164373836
          64643364333732383333623432373866323132613861616266343639623362396234396136323163
          3061393739376361630a323835633935363631376566643638343338356430353134616266616236
          3035
all_areas:
  area0:
    type: "standard"
    routers: 3
    drs: 1
  area1:
    type: "standard"
    routers: 2
    drs: 0
    has_frr: false
    max_lsa3: 3333
  area2:
    type: "stub"
    routers: 2
    drs: 1
  area3:
    type: "standard"
    routers: 2
    drs: 0
  area4369:
    type: "nssa"
    routers: 3
    drs: 0
    has_frr: true
    max_lsa3: 333
    max_lsa7: 777
...
